### ISSUE TITLE
Wrong order of images if frame count exceeds 1000

### ISSUE THREAD

**Issue by lostdisplay** [Comeza/image-stitch#1]
By the time it loads the 100th image it will jump to the 1000th one. 
Which makes a chronological order by naming it _"1", "2", "3", "4", "5"_ (wrong, it was "001", "002", "003"...) etc. impossible if your total frame count exceeds 1000 images.

![Screenshot 2021-03-09 003742](https://user-images.githubusercontent.com/57991867/110396108-ae5d3000-806f-11eb-8ebf-ad1be0bc8416.jpg)

**Comment by Streamfire** [comment]
you mean image order is wrong if there are no leading 0s in the filename

**Comment by lostdisplay** [comment]
^ above is right.
![Screenshot 2021-03-09 005245](https://user-images.githubusercontent.com/57991867/110397291-e1082800-8071-11eb-8163-705425f5f050.jpg)

The number should contain as many digits as the last frame has.
My example project had 1440 images and only the images up to the two digit frame count contained leading zeros in the filename.

**Comment by Comeza** [comment]
fixed in 590a014a254a339d9dddcffcf7513053b2cb4f00
